#!/usr/bin/with-contenv ash

# default value

NAS_IP=${NAS_IP:-""}
NAS_SSH_PORT=${NAS_SSH_PORT:-"22"}
NAS_SSH_USER=${NAS_SSH_USER:-"root"}
NAS_SSH_PASS=${NAS_SSH_PASS:-""}
NAS_SCRIPTS_POS=${NAS_SCRIPTS_POS:-"/usr/local/bin"}

BACKUP_SOURCES=${BACKUP_SOURCES:-""}
BACKUP_DESTINATION=${BACKUP_DESTINATION:-""}

BACKUP_MIN_DELAY=${BACKUP_MIN_DELAY:-"0"}    # right now
BACKUP_MAX_DELAY=${BACKUP_MAX_DELAY:-"3600"} # 1h

# tools

sleep $(( $BACKUP_MIN_DELAY + $RANDOM % $BACKUP_MAX_DELAY ))

log="cd $BACKUP_DESTINATION; $NAS_SCRIPTS_POS/log"
today=$(date +%Y%m%d)

echo "backup $today rsync log" > /tmp/rsync.log
sshpass -p "$NAS_SSH_PASS" ssh -oStrictHostKeyChecking=no -p $NAS_SSH_PORT $NAS_SSH_USER@$NAS_IP "$log 'Starting Backup'"

for SOURCE in $BACKUP_SOURCES;
do
	echo "--------------------------" >> /tmp/rsync.log
	sshpass -p "$NAS_SSH_PASS" rsync -e "ssh -oStrictHostKeyChecking=no -p $NAS_SSH_PORT" -azv --del $SOURCE $NAS_SSH_USER@$NAS_IP:$BACKUP_DESTINATION/current >> /tmp/rsync.log
	sshpass -p "$NAS_SSH_PASS" ssh -oStrictHostKeyChecking=no -p $NAS_SSH_PORT $NAS_SSH_USER@$NAS_IP "$log '$SOURCE succesfuly rsync in current'"
done


sshpass -p "$NAS_SSH_PASS" rsync -e "ssh -oStrictHostKeyChecking=no -p $NAS_SSH_PORT" -zP /tmp/rsync.log $NAS_SSH_USER@$NAS_IP:$BACKUP_DESTINATION/current
sshpass -p "$NAS_SSH_PASS" ssh -oStrictHostKeyChecking=no -p $NAS_SSH_PORT $NAS_SSH_USER@$NAS_IP "$log 'rsync logs in current/rsync.log'"
sshpass -p "$NAS_SSH_PASS" ssh -oStrictHostKeyChecking=no -p $NAS_SSH_PORT $NAS_SSH_USER@$NAS_IP "cd $BACKUP_DESTINATION; $NAS_SCRIPTS_POS/mv_backups"

